name: Docker image build

on:
  repository_dispatch:
  workflow_dispatch:  # for manual testing
  push: # for testing

jobs:
  docker-build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download executable
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4  # v1.10.0
        with:
          repo: tezz123/mondootest
          extension-matching: false
          platform: linux
          arch: x86_64
          chmod: 0755
          rename-to: mondoohelloworld
      - name: Docker metadata
        uses: docker/metadata-action@v5.5.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and release Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
