name: Docker image build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'GH Release Tag'
        required: true

jobs:
  docker-build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download executable
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4  # v1.10.0
        with:
          repo: tezz123/mondootest
          extension-matching: false
          platform: linux
          arch: amd64
          chmod: 0755
          rename-to: mondoohelloworld
          tag: ${{ inputs.tag }}
      - name: move the binary
        run: mv /opt/hostedtoolcache/tezz123/mondootest/${{ inputs.tag }}/linux-amd64/mondoohelloworld-linux-amd64 mondoohelloworld
      - name: Docker metadata
        uses: docker/metadata-action@v5.5.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and release Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/tezz123/mondootest2:${{ inputs.tag }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Update Image Tag
        uses: mikefarah/yq@4cc646b16b481a305c45e5eafa920c03c77565ea  # 4.44.1
        with:
          cmd: yq --inplace '.image.tag = "${{ inputs.tag }}"' helm/values.yaml
      - name: Helm Lint
        run: helm lint helm
      - name: Commit back to git
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5  # v9.1.4
        with:
          author_name: Pavo
          author_email: foo@bar.com
          message: "Update version to ${{ inputs.tag }}"
          add: "helm/values.yaml"
